import pandas as pd

# The exact tests your model failed on
tests = [
    ("Gemini Hi maran What should we do next? What's a totally different career where you could see me thriving? Recommend a documentary based on what I've been curious about 🔮 For you 🖼️ Create image 🏏 Explore IPL Fan Zone 🎸 Create music 📄 Write anything Ask Gemini Fast", "safe"),
    ("who was b", "safe"),
    ("Actually this feature", "safe"),
    ("Wait b", "safe"),
    ("So 45 m", "safe"),
    ("So 45 minutes is no", "safe"),
    ("So then who the man 3xsit", "safe"),
    ("neet pg dates", "education"),
    ("13% (2m left) • 20 MB", "safe"),
    ("no more quality 5est", "safe"),
    ("here lau", "safe"),
    ("doesn't ubd", "safe"),
    ("080 6217 8718", "safe"),
    ("How download f", "safe"),
    ("GATE Phase 2 Cheat Sheet PDF 3.pdf", "education"),
    ("I am ready for Phase 2: The GATE Wrap-Up Cheat Sheet", "education"),
    ("Downloads Downloads Images Audio Videos Documents Large files This week Files in Downloads Downloads", "safe"),
    ("Search \"ticket\"", "safe"),
    ("Ready for set 5", "safe"),
    ("Now it is time switch next role that is from", "safe"),
    ("Okay this grand finale o", "safe"),
    ("It is my mistake 6", "safe"),
    ("Sorry my mistake 5hr", "safe"),
    ("6 pdf sorry", "safe"),
    ("Share screen with Live", "safe"),
    ("56/2,268 Share Edit Delete More", "safe"),
    ("Hi sir, recently I call you for the fiappointment", "business"),
    ("Copy Edit Retry", "safe"),
    ("What's on your mind? What impact does dew have on T20 matches? Generate a practice test for Class 10 History: Nationalism in India Ask anything", "education"),
    ("dc songs", "entertainment"),
    ("song download app", "entertainment"),
    ("Search Google Photos Photos Collections May 2 Preview Done", "safe"),
    ("View Model Card on Hugging Face", "technology"),
    ("npu p", "technology"),
    ("Downloads Downloads Large files This week Downloads", "safe"),
    ("wynk music", "entertainment"),
    ("Downloads Downloads Images Audio Videos Documents Large files This week Downloads", "safe"),
    ("i wan", "safe"),
    ("See the screenshot please", "safe"),
    ("Sorry ocr to odf", "technology"),
    ("Describe your video", "safe"),
    ("I want this type of monochrome on behalf my photo attached", "safe"),
    ("Search Google Photos Photos Collections May 1 Preview Done", "safe"),
    ("Today 9:41 PM Share Edit Delete More", "safe"),
    ("Share Copy Save", "safe"),
    ("But i want same clothes and same face from the original but camera angle and face", "safe"),
    ("But i want same clothes and same face from the original but camera angle and face postion was", "safe"),
    ("Can I get photo same angle from the monochrome reference photo which there", "safe"),
    ("gemma 3 download", "technology"),
    ("Then why youtube channel i am", "safe"),
    ("windows update stuck at 99%", "technology"),
    ("ERR_CONNECTION_TIMED_OUT how to fix", "technology"),
    ("why is my laptop screen flickering", "technology"),
    ("bluetooth mouse keeps disconnecting windows 11", "technology"),
    ("dns_probe_finished_nxdomain fix", "technology"),
    ("what is the weather like today", "safe"),
    ("nearest grocery store open now", "safe"),
    ("directions to the nearest gas station", "safe"),
    ("is it going to rain tomorrow", "safe"),
    ("coffee shops near me", "safe")
]

df_new = pd.DataFrame(tests, columns=["text", "label"])
df_new.to_csv("training_data.csv", mode='a', header=False, index=False)

print(f"✅ Successfully added {len(tests)} new examples to training_data.csv!")
print("Next step: Run `python train_transformer_tf.py` to retrain the AI on this new data.")